#!/bin/sh

# Path to molecules.git dir
SABAYON_MOLECULE_HOME="${SABAYON_MOLECULE_HOME:-/sabayon}"
export SABAYON_MOLECULE_HOME

# rootfs and bootfs tarball is generated by image
export FIRST_PARTITION_START_CYL=1 # ~8Mb
export SD_FUSE="${SABAYON_MOLECULE_HOME}/boot/arm/bananapi/sd_fuse/sd_fusing.sh"
export BOOT_PART_TYPE_INSIDE_ROOT="1"
exec "${SABAYON_MOLECULE_HOME}"/scripts/mkloopcard.sh "${SABAYON_MOLECULE_HOME}"/scripts/mkloopcard_bananapi_generic_hook.sh "${@}"
